### PR TITLE
Service reference update

### PR DESCRIPTION
**Pull request by RyanMcKennon**

### CODE REVIEW

**Comment by fredrevature** [comment]
@polseane9067 this branch is not ready to be merged. @RyanMcKennon is still working on it.

**Comment by fredrevature** [comment]
anytime will do. 😄

**Comment by RyanMcKennon** [comment]
please merge this

**Comment by RyanMcKennon** [comment]
weird okay now merge this

**Comment by RyanMcKennon** [comment]
that commit is showing below my comment, I still need it merged. Thanks

**Comment by RyanMcKennon** [comment]
okay now merge it i promise it's ready now

**Pull request merged**
