### PR TITLE
Rider validation

### PR DESCRIPTION
**Pull request by RyanMcKennon**
Fixed a bug within the rider section of the code that was returning only the user names instead of the entire rides.

Fixed a bug within the driver section of the code for viewing passengers that was returning a user instead of a ride riders object

### CODE REVIEW

**Comment by RyanMcKennon** [comment]
ready to merge

**Comment by RyanMcKennon** [comment]
it's really ready to merge. Github is being dumb that comment is after my commit.

**Comment by SoxKeepYouWarm** [comment]
Have you checked with the frontend team on some of those changes?  I see you changed the return type of getRides to return a list of rideRiders instead of Ride objects.  The original intent of that function is return a list of rides posted by drivers, not pairings between drivers and riders.

**Comment by RyanMcKennon** [comment]
ready to merge brother bear

**Pull request merged**
